server:
    port: 28080

spring:

    datasource:
        url: jdbc:h2:mem:default
#        url: jdbc:postgresql://localhost:5433/postgres?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
        username:
        password:
        driver-class-name: org.h2.Driver
    jpa:
        database-platform:
        database: h2
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    main:
        log-startup-info: false

