spring:

    datasource:
        url: jdbc:h2:mem:default
        username:
        password:
        driver-class-name: org.h2.Driver
    jpa:
        database: h2

    liquibase:
        change-log: classpath:db/changelog/db-with-sample-data.xml
